### PR TITLE
[TM Only Please] Ports Skyrat Character Customization.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Ports snowflake customization from https://github.com/Skyrat-SS13/Skyrat-tgmc/pull/7 which was ported from Skyrat proper. 

In other words you can now create and play most of your terrible creations. More customization to hopefully come later. 
While I did test to make sure it wasn't completely broken, there may be minor bugs.

## Why It's Good For The Game

This is basically a priority one feature for the server.

## Changelog
:cl: Tupinambis
add: Added Skyrat character customization.
soundadd: Added various screams to pick from.
imageadd: Added a bunch of sprites for character customization.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
There's no actual testmerge system available yet for the server, but once we get that up I'll prioritise this.
Until then, there's a few line endings that need fixing:
https://github.com/ProbablySpaghetti/XRF-13/pull/7/checks?check_run_id=2871578906#step:5:121

**Comment by ghost** [comment]
Testmerge system is up and running now, so please clear up those errors and I'll get this running.

**Comment by pantherpusher** [comment]
cmon we're so close

**Comment by Guidesu** [comment]
grep: code/**/*.dmm: No such file or directory

The last error

**Comment by Guidesu** [comment]
infact. There's actually no errors at all

**Comment by SabreML** [comment]
Error seems to be coming from dreamchecker this time, under 'Annotate Lints' (for some reason).
```
DreamChecker Output: 
============================================================
Parsing tgmc.dme...

============================================================
Analyzing variables...

============================================================
Gathering proc settings...

============================================================
Analyzing proc bodies...

code/__HELPERS/sanitize_values.dm, line 125, column 2:
error: possible unreachable code here

Procs analyzed: 14981. Errored: 0. Builtins: 335.

============================================================
Analyzing proc override validity...

============================================================
Analyzing proc call tree...

============================================================
Found 1 diagnostics
```

**Comment by ghost** [comment]
Error seems to be coming from dreamchecker this time, which is under 'Annotate Lints' (for some reason).
```
DreamChecker Output: 
============================================================
Parsing tgmc.dme...

============================================================
Analyzing variables...

============================================================
Gathering proc settings...

============================================================
Analyzing proc bodies...

code/__HELPERS/sanitize_values.dm, line 125, column 2:
error: possible unreachable code here

Procs analyzed: 14981. Errored: 0. Builtins: 335.

============================================================
Analyzing proc override validity...

============================================================
Analyzing proc call tree...

============================================================
Found 1 diagnostics
```

**Comment by chaoko99** [comment]
Several comments:
Vatborns have been straight up deleted with no mention of that.
The sprite preview for humans appears to break completely upon any modifications.

**Comment by Guidesu** [comment]
> Several comments:
> Vatborns have been straight up deleted with no mention of that.
> The sprite preview for humans appears to break completely upon any modifications.

All upstream issues

**Comment by chaoko99** [comment]
Are they going to be fixed?

**Pull request merged**
