### PR TITLE
Fixes issue #12

### LINKED ISSUE #12: Chemrette packet box fix
change line to `	icon_state = "[initial(icon_state)]box[contents.len]"` at line 205, possible fix.

https://github.com/ProbablySpaghetti/XRF-13/blob/d89cfb4d0978e609d955301593132d14bcf298f6/code/game/objects/items/storage/fancy.dm#L205

### PR DESCRIPTION
**Pull request by UntoldTactics**
## About The Pull Request
Fixes #12 
Tested and works, far as I can tell.

## Why It's Good For The Game
Fixes a bug that made chemrette packets invisible at any state beyond the default state (when all items are inside it)
Fixes issue #12 

## Changelog
:cl:
fix: Chemrette packets are now visible
/:cl:

### CODE REVIEW

**Comment by EnRet** [comment]
Do it, you won't

**Review by ghost — COMMENTED** [review]
May be better to rename the icon states in `\icons\obj\items\cigarettes.dmi` and remove the 'box' part rather than adding it here, that way it stays consistent with everything else in that file.

(Also if you put `Fixes #12` specifically in the PR description it'll automatically close the PR when this is merged)

**Comment by UntoldTactics** [comment]
> May be better to rename the icon states in `\icons\obj\items\cigarettes.dmi` and remove the 'box' part rather than adding it here, that way it stays consistent with everything else in that file.
> 
> (Also if you put `Fixes #12` specifically in the PR description it'll automatically close the PR when this is merged)

I tried, didn't work, can't be bothered to figure out why.

**Comment by ghost** [comment]
Eh, this is fine then.

**Pull request merged**
